# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: barba.js
subtitle:
description:
keywords:
author: Barba team
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://barba.js.org
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Navigation
## Menu Navigation
menu:
- title:  'Features'
  url:    '/features/dependency-free'
  slug:   '/features'
  subpages:
    - title:    'Dependency Free'
      url:      '/features/dependency-free'
      modifier: 'dependency-free'
    - title:    'Small size'
      url:      '/features/small-size'
      modifier: 'small-size'
    - title:    'Open Source'
      url:      '/features/open-source'
      modifier: 'open-source'
    - title:    'Views/Namespaces Logic'
      url:      '/features/views-namespaces-logic'
      modifier: 'views-namespaces-logic'
    - title:    'Prefetch'
      url:      '/features/prefetch'
      modifier: 'prefetch'
    - title:    'Change Log'
      url:      '/features/change-log'
      modifier: 'change-log'
- title:  'About'
  url:    '/about'
  slug:   '/about'
- title:  'Example'
  url:    '/example'
  slug:   '/example'
- title:  'Showcase'
  url:    '/showcase'
  slug:   '/showcase'
- title:  'Docs'
  url:    '/docs/getstarted/intro'
  slug:   '/docs'

### Docs Navigation
docs:
- title:  'Get Started'
  url:    '/docs/getstarted/intro'
  path:   '/docs/getstarted'
  nextpage:
      label:  'USER GUIDE'
      slug:   '/docs/userguide/markup'
- title:  'User Guide (Core)'
  url:    '/docs/userguide/markup'
  path:   '/docs/userguide'
  subpages:
    - title:  'Markup'
      url:    '/docs/userguide/markup'
      prevpage:
          label:  'GET STARTED'
          slug:   '/docs/getstarted/intro'
      nextpage:
          label:  'Syntax'
          slug:   '/docs/userguide/syntax'
    - title:  'Syntax'
      url:    '/docs/userguide/syntax'
      prevpage:
          label:  'Markup'
          slug:   '/docs/userguide/markup'
      nextpage:
          label:  'PLUGINS'
          slug:   '/docs/plugins/css'
- title:  'Plugins'
  url:    '/docs/plugins/css'
  path:   '/docs/plugins'
  subpages:
    - title:  'Css'
      url:    '/docs/plugins/css'
      prevpage:
          label:  'USER GUIDE'
          slug:   '/docs/userguide/markup'
      nextpage:
          label:  'Router'
          slug:   '/docs/plugins/router'
    - title:  'Router'
      url:    '/docs/plugins/router'
      prevpage:
          label:  'Css'
          slug:   '/docs/plugins/css'
      nextpage:
          label:  'Prefetch'
          slug:   '/docs/plugins/prefetch'
    - title:  'Prefetch'
      url:    '/docs/plugins/prefetch'
      prevpage:
          label:  'Router'
          slug:   '/docs/plugins/router'
      nextpage:
          label:  'Transitions'
          slug:   '/docs/plugins/transitions'
    - title:  'Transitions'
      url:    '/docs/plugins/transitions'
      prevpage:
          label:  'Prefetch'
          slug:   '/docs/plugins/prefetch'
      nextpage:
          label:  'Head'
          slug:   '/docs/plugins/head'
    - title:  'Head'
      url:    '/docs/plugins/head'
      prevpage:
          label:  'Transitions'
          slug:   '/docs/plugins/transitions'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: barba

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# SASS
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false

browsersync:
  logLevel: "warn"
  ghostMode:
    scroll: true
  instanceName: "uniqueString"
