# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: barba.js
subtitle:
description: Create badass, fluid and smooth transition between your website's pages.
keywords:
author: Barba team
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://barba.js.org
root: /preview/v2/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :layout/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Navigation
## Menu Navigation
menu:
  - title: 'Features'
    url: 'features/fast-flexible'
    slug: '/features'
    subpages:
      - title: 'User friendly'
        url: 'features/user-friendly'
      - title: 'Easy peasy'
        url: 'features/easy-peasy'
      - title: 'Smart'
        url: 'features/smart'
      - title: 'Extensible'
        url: 'features/extensible'
      - title: 'Futureproof'
        url: 'features/futureproof'
      - title: 'Community'
        url: 'features/community'
  - title: 'Examples'
    url: 'examples'
    slug: '/examples'
  - title: 'Showcase'
    url: 'showcase'
    slug: '/showcase'
  - title: 'Docs'
    url: 'docs/getstarted/intro'
    slug: '/docs'

### Docs Navigation
docs:
  - title: 'Get Started'
    url: 'docs/getstarted/intro'
    path: 'docs/getstarted'
    nextpage:
      label: 'USER GUIDE'
      url: 'docs/userguide/markup'
  - title: 'User Guide (Core)'
    url: 'docs/userguide/markup'
    path: 'docs/userguide'
    subpages:
      - title: 'Markup'
        url: 'docs/userguide/markup'
      - title: 'Syntax'
        url: 'docs/userguide/syntax'
  - title: 'Plugins'
    url: 'docs/plugins/css'
    path: 'docs/plugins'
    subpages:
      - title: 'Css'
        url: 'docs/plugins/css'
      - title: 'Router'
        url: 'docs/plugins/router'
      - title: 'Prefetch'
        url: 'docs/plugins/prefetch'
      - title: 'Preset'
        url: 'docs/plugins/preset'
      - title: 'Head'
        url: 'docs/plugins/head'

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: barba

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# SASS
node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false

browsersync:
  logLevel: 'warn'
  ghostMode:
    scroll: true
  instanceName: 'uniqueString'
