version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.15.1-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore Node modules
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Bootstrap Lerna monorepo
          command: yarn run bootstrap
      - persist_to_workspace:
          root: ~/barba-next
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/barba-next
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Bundle
          command: yarn run build
      - run:
          name: Test
          command: yarn run unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
