version: 2.1

executors:
  node-lts:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts

jobs:
  deploy:
    executor: node-lts
    steps:
      - checkout
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages@2.0.1
            git config user.email $GH_EMAIL
            git config user.name $GH_NAME
      - add_ssh_keys:
          fingerprints:
            - '2c:bd:91:1f:35:54:de:94:22:77:fc:3e:68:f9:6b:2f'
      - run:
          name: Deploy website to gh-pages branch
          command: ./node_modules/.bin/gh-pages -d www -e v1 -m 'Deploy website [ci skip]'

workflows:
  website_v1:
    jobs:
      - deploy:
          filters:
            branches:
              only: website-1.x
